### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by MaxGfeller** [sssmi/vue-combo-blocks#12]
Hi @sssmi 👋  

Thanks for the great library! Is support for Vue 3 planned? I'm not sure what all would have to be done, but currently it breaks already at the Vue import:

```bash
"export 'default' (imported as 'Vue') was not found in 'vue'
```

**Comment by sssmi** [comment]
Hi thanks for the feedback 👍
I will probably make a version for Vue 3 soon.

**Comment by sssmi** [comment]
Vue 3 support #22
Run `npm i vue-combo-blocks@next`
